# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Mutation tests"

on:
    pull_request:
    push:
        branches:
            - "master"
            - "renovate/*"

jobs:
    mutation-tests:
        name: "Mutation tests"

        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                dependencies:
                    - "locked"
                php-version:
                    - "8.1"
                operating-system:
                    - "ubuntu-latest"

        steps:
            - name: "Checkout"
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

            - name: "Install PHP"
              uses: "shivammathur/setup-php@2.35.4"
              with:
                  coverage: "pcov"
                  php-version: "${{ matrix.php-version }}"
                  ini-values: memory_limit=-1

            - uses: ramsey/composer-install@3.1.1
              with:
                dependency-versions: ${{ matrix.dependencies }}

            - name: "Infection"
              run: "vendor/bin/infection"
              env:
                  STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
