# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Static Analysis by Psalm"

on:
    pull_request:
    push:
        branches:
            - "master"
            - "renovate/*"

jobs:
    static-analysis-psalm:
        name: "Static Analysis by Psalm"

        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                dependencies:
                    - "locked"
                php-version:
                    - "8.1"
                operating-system:
                    - "ubuntu-latest"

        steps:
            - name: "Checkout"
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

            - name: "Install PHP"
              uses: "shivammathur/setup-php@2.25.1"
              with:
                  coverage: "pcov"
                  php-version: "${{ matrix.php-version }}"
                  ini-values: memory_limit=-1

            - uses: ramsey/composer-install@2.2.0
              with:
                dependency-versions: ${{ matrix.dependencies }}

            - name: "psalm"
              run: "vendor/bin/psalm --shepherd --stats"
